# Generated by Django 5.1 on 2024-08-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp3', '0002_vol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vol',
        ),
    ]
