# Generated by Django 5.1 on 2024-08-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp3', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
